services:
  profile_service: &profile_service_base
    image: node:18
    container_name: profile_service
    working_dir: /app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      URL_CONNECT: ${URL_CONNECT}
    volumes:
      - ./profile-service:/app:z
    command: sh -c "npm install && npm run start"
    ports:
      - "3004:3000"
    depends_on:
      - postgres_1
      - postgres_2
      - postgres_3
  
  profile_service_replica:
    <<: *profile_service_base # Copia toda la configuración de arriba
    container_name: profile_service_replica
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      URL_CONNECT: ${URL_CONNECT}
      IS_REPLICA: "true"
    ports:
      - "3005:3000"
