events {}

#  Controlar el area de Reverse-Proxy
http {
    # Establecer servicios
    upstream Auth_Service {
        server microservicioAuth:3000;
        server microservicioAuth_replica:3000;
    }

    upstream Profile_Service {
        server profile_service:3000;
        server profile_service_replica:3000;
    }

    upstream Image_Service {
        server image_service:3000;
        server image_service_replica:3000;
    }

    server {
        listen 80;

        # Va a escuchar en la raiz, a nuestros dos servidores
        location /auth/{
            proxy_pass http://Auth_Service/;

            # Las cabeceras las vamos a mandar a mi host, es decir las recibimos en nginx y las mandamos al backend
            proxy_set_header HOST $host;

            # Para que el backend sepa la ip del cliente, no la ip del contenedor de nginx
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /profile/{
            proxy_pass http://Profile_Service/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /image/{
            proxy_pass http://Image_Service/;

            # Las cabeceras las vamos a mandar a mi host, es decir las recibimos en nginx y las mandamos al backend
            proxy_set_header HOST $host;

            # Para que el backend sepa la ip del cliente, no la ip del contenedor de nginx
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}